CREATE TABLE `Step_Up_Ost`(
`Num`INT(11) NOT NULL AUTO_INCREMENT,
`Title` VARCHAR(200) NOT NULL,
`Artist` VARCHAR(200) NOT NULL,
`Album` VARCHAR(200) NOT NULL,
`Playtime` VARCHAR(50) NOT NULL,
PRIMARY KEY (`num`) USING BTREE 
)

select * from Step_Up_Ost
